export const categories = ["All", "Main Course", "Starters", "Desserts", "Breads"];

export const sampleMenuItems = [
    {
        id: "1",
        name: "Classic Chicken Biryani",
        description: "Aromatic basmati rice cooked with tender chicken pieces, secret spices, and love. Served with raita.",
        price: 350,
        image_url: "/assets/biryani.jpg",
        category: "Main Course",
        is_available: true,
        spice_level: "Medium",
        dietary_tags: ["Non-Veg"],
    },
    {
        id: "2",
        name: "Paneer Butter Masala",
        description: "Soft paneer cubes in a rich, creamy tomato and cashew gravy.",
        price: 280,
        image_url: "/assets/paneer.jpg",
        category: "Main Course",
        is_available: true,
        spice_level: "Mild",
        dietary_tags: ["Veg", "Contains Dairy"],
    },
    {
        id: "3",
        name: "Mutton Nalli Nihari",
        description: "Slow-cooked mutton shanks in a deeply flavorful bone-marrow enriched stew.",
        price: 550,
        image_url: "https://images.unsplash.com/photo-1539755530862-00f623c00f52?q=80&w=800&auto=format&fit=crop",
        category: "Main Course",
        is_available: true,
        spice_level: "Spicy",
        dietary_tags: ["Non-Veg"],
    },
    {
        id: "4",
        name: "Chicken Tikka Kebab",
        description: "Juicy, smoky boneless chicken chunks marinated in yogurt and spices, grilled to perfection.",
        price: 300,
        image_url: "/assets/chicken_tikka.jpg",
        category: "Starters",
        is_available: true,
        spice_level: "Medium",
        dietary_tags: ["Non-Veg"],
    },
    {
        id: "5",
        name: "Garlic Butter Naan",
        description: "Soft, fluffy Indian flatbread brushed with garlic-infused butter.",
        price: 60,
        image_url: "/assets/butter_naan.jpg",
        category: "Breads",
        is_available: true,
        spice_level: "None",
        dietary_tags: ["Veg", "Contains Dairy", "Contains Gluten"],
    },
    {
        id: "6",
        name: "Shahi Tukda",
        description: "A royal dessert of fried bread soaked in milk with saffron, cardamom, and nuts.",
        price: 150,
        image_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=800&auto=format&fit=crop",
        category: "Desserts",
        is_available: true,
        spice_level: "None",
        dietary_tags: ["Veg", "Contains Dairy"],
    }
];
